export const BINDER_CATALOG = [
  {
    id: 'starter-sleeve',
    name: 'Starter Sleeve',
    capacity: 2,
    price: 100,
    rarity: 'common',
    theme: 'simple leather',
    description: 'A compact leather sleeve for your first treasured pulls.',
    colors: { primary: '#5a3a24', secondary: '#1b1410', accent: '#d6a15c' },
    visualType: 'leather',
    unlockText: 'A humble first home for favorite cards.',
  },
  {
    id: 'apprentice-binder',
    name: 'Apprentice Binder',
    capacity: 5,
    price: 250,
    rarity: 'common',
    theme: 'blue arcane',
    description: 'Blue arcane filigree wraps a small spellbook-style binder.',
    colors: { primary: '#1c5f8f', secondary: '#101b33', accent: '#8fe5ff' },
    visualType: 'arcane',
    unlockText: 'Perfect for a growing apprentice archive.',
  },
  {
    id: 'planeswalker-folio',
    name: 'Planeswalker Folio',
    capacity: 10,
    price: 500,
    rarity: 'uncommon',
    theme: 'purple magic',
    description: 'A violet folio with planeswalking sigils and soft mana glow.',
    colors: { primary: '#6847c7', secondary: '#160f2e', accent: '#d5c7ff' },
    visualType: 'sigil',
    unlockText: 'Carry a small collection across worlds.',
  },
  {
    id: 'guild-archive',
    name: 'Guild Archive',
    capacity: 15,
    price: 900,
    rarity: 'uncommon',
    theme: 'gold city guild',
    description: 'A city-guild archive stamped with polished gold lines.',
    colors: { primary: '#8a6a21', secondary: '#1c1f2a', accent: '#f4c95d' },
    visualType: 'guild',
    unlockText: 'A formal archive for organized pulls.',
  },
  {
    id: 'dragonhide-binder',
    name: 'Dragonhide Binder',
    capacity: 25,
    price: 1500,
    rarity: 'rare',
    theme: 'red dragon scale',
    description: 'Embossed crimson scales and ember glow protect rare hits.',
    colors: { primary: '#9d2e27', secondary: '#1f0908', accent: '#ff8a3d' },
    visualType: 'scales',
    unlockText: 'Built for fiery favorites and serious pulls.',
  },
  {
    id: 'moonlit-grimoire',
    name: 'Moonlit Grimoire',
    capacity: 35,
    price: 2500,
    rarity: 'rare',
    theme: 'silver moon magic',
    description: 'A silver-blue grimoire with moonlit borders and quiet glow.',
    colors: { primary: '#8aa4bd', secondary: '#111827', accent: '#dbeafe' },
    visualType: 'moon',
    unlockText: 'A luminous vault for night-bound magic.',
  },
  {
    id: 'vault-of-relics',
    name: 'Vault of Relics',
    capacity: 50,
    price: 4000,
    rarity: 'rare',
    theme: 'ancient treasure vault',
    description: 'Ancient bronze plating and relic light make this feel heavy.',
    colors: { primary: '#9a6a31', secondary: '#15100a', accent: '#ffd27a' },
    visualType: 'vault',
    unlockText: 'A treasure vault for a serious collection.',
  },
  {
    id: 'eldritch-codex',
    name: 'Eldritch Codex',
    capacity: 65,
    price: 6000,
    rarity: 'mythic',
    theme: 'green/black cosmic horror',
    description: 'Black-green cosmic runes twist across an unsettling codex.',
    colors: { primary: '#1f7a4d', secondary: '#050a08', accent: '#adff2f' },
    visualType: 'eldritch',
    unlockText: 'For collectors who enjoy impossible archives.',
  },
  {
    id: 'celestial-atlas',
    name: 'Celestial Atlas',
    capacity: 80,
    price: 8000,
    rarity: 'mythic',
    theme: 'star map celestial',
    description: 'A star-map binder with celestial routes and radiant constellations.',
    colors: { primary: '#2f5edb', secondary: '#090d24', accent: '#f8f7ff' },
    visualType: 'stars',
    unlockText: 'Chart your pulls across the night sky.',
  },
  {
    id: 'eternal-archive',
    name: 'Eternal Archive',
    capacity: 100,
    price: 10000,
    rarity: 'legendary',
    theme: 'premium black/gold legendary archive',
    description: 'A premium black and gold archive worthy of a legendary collection.',
    colors: { primary: '#111111', secondary: '#020202', accent: '#f4c95d' },
    visualType: 'legendary',
    unlockText: 'The final archive for your most prized cards.',
  },
];

export function getCatalogBinderById(binderId) {
  return BINDER_CATALOG.find((binder) => binder.id === binderId) || null;
}
