export const RED_STARTER_ENEMY_DECK_NAMES = [
  'Lightning Bolt',
  'Shock',
  'Lightning Strike',
  'Play with Fire',
  'Monastery Swiftspear',
  'Goblin Guide',
  'Viashino Pyromancer',
  'Ghitu Lavarunner',
  'Bonecrusher Giant',
  'Kumano Faces Kakkazan',
  'Phoenix Chick',
  'Feldon, Ronom Excavator',
  "Chandra's Pyrohelix",
  'Searing Spear',
  'Abrade',
  'Volcanic Spite',
  'Furnace Punisher',
  'Reckless Stormseeker',
  'Shivan Dragon',
  'Chandra, Dressed to Kill',
];
