export const SHOP_CATEGORIES = {
  THEMES: 'themes',
  OPENING_SCENES: 'openingScenes',
  SLEEVES: 'sleeves',
  TEAR_EFFECTS: 'tearEffects',
  REVEAL_EFFECTS: 'revealEffects',
  PROFILE_COSMETICS: 'profileCosmetics',
  BINDER_COSMETICS: 'binderCosmetics',
  DISPLAY_CASES: 'displayCases',
  TRADE_SKINS: 'tradeSkins',
  HISTORY_FRAMES: 'historyFrames',
  HOME_WIDGETS: 'homeWidgets',
};

const EQUIP_SLOTS = {
  APP_THEME: 'appTheme',
  OPENING_SCENE: 'openingScene',
  CARD_SLEEVE: 'cardSleeve',
  TEAR_EFFECT: 'tearEffect',
  REVEAL_EFFECT: 'revealEffect',
  TRADE_SKIN: 'tradeSkin',
  AVATAR_FRAME: 'avatarFrame',
  PROFILE_BANNER: 'profileBanner',
  TITLE_BADGE: 'titleBadge',
};

export const SHOP_CATALOG = [
  {
    id: 'theme-arcane-midnight',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Arcane Midnight',
    description: 'A deep midnight interface with quiet violet magic and gold accents.',
    price: 1200,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#090b18', '#6f63ff', '#f4c95d'],
    cssClass: 'cosmeticTheme-arcaneMidnight',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'theme-gilded-vault',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Gilded Vault',
    description: 'A polished vault theme with dark metal surfaces and gilded highlights.',
    price: 1600,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#080808', '#c9962e', '#fff0b8'],
    cssClass: 'cosmeticTheme-gildedVault',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'theme-galaxy-archive',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Galaxy Archive',
    description: 'A cosmic archive theme with starfield blues and nebula violet.',
    price: 1500,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#050716', '#3c7bff', '#b45cff'],
    cssClass: 'cosmeticTheme-galaxyArchive',
    unlockType: 'cosmetic',
  },
  {
    id: 'theme-dragonfire',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Dragonfire',
    description: 'A hot ember theme with charred blacks, crimson glow, and molten gold.',
    price: 1400,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#120705', '#d73a22', '#ffb347'],
    cssClass: 'cosmeticTheme-dragonfire',
    unlockType: 'cosmetic',
  },
  {
    id: 'theme-moonlit-silver',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Moonlit Silver',
    description: 'A cool silver theme with moonlit blues and clean white highlights.',
    price: 1100,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#111827', '#9fb7d6', '#f7f8ff'],
    cssClass: 'cosmeticTheme-moonlitSilver',
    unlockType: 'cosmetic',
  },
  {
    id: 'theme-neon-ink',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Neon Ink',
    description: 'A vivid neon theme with electric cyan, magenta, and blacklight contrast.',
    price: 1800,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#03040a', '#00ffff', '#ff00c8'],
    cssClass: 'cosmeticTheme-neonInk',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'theme-eldritch-green',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Eldritch Green',
    description: 'A strange green theme with ancient glow and shadowed surfaces.',
    price: 1300,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#06120c', '#38d978', '#b6ffbd'],
    cssClass: 'cosmeticTheme-eldritchGreen',
    unlockType: 'cosmetic',
  },
  {
    id: 'theme-classic-card-shop',
    category: SHOP_CATEGORIES.THEMES,
    name: 'Classic Card Shop',
    description: 'A familiar tabletop-shop theme with warm neutrals and practical contrast.',
    price: 800,
    rarity: 'uncommon',
    equipSlot: EQUIP_SLOTS.APP_THEME,
    previewColors: ['#16120d', '#b6854d', '#f4d29b'],
    cssClass: 'cosmeticTheme-classicCardShop',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-mystic-tabletop',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Mystic Tabletop',
    description: 'Open packs over a spell-lit playmat with subtle arcane ambience.',
    price: 900,
    rarity: 'uncommon',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#151326', '#785ef0', '#f4c95d'],
    cssClass: 'openingScene-mysticTabletop',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-ancient-library',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Ancient Library',
    description: 'Open packs among old shelves, candlelight, and forgotten lore.',
    price: 1100,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#100d0a', '#8f6a3e', '#e7c16d'],
    cssClass: 'openingScene-ancientLibrary',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-cosmic-void',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Cosmic Void',
    description: 'Open packs in a silent starfield with deep space color.',
    price: 1500,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'openingScene-cosmicVoid',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'scene-treasure-vault',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Treasure Vault',
    description: 'Open packs inside a locked vault of coins, relics, and warm gold.',
    price: 1400,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#080806', '#d6a33a', '#fff1a8'],
    cssClass: 'openingScene-treasureVault',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-moonlit-temple',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Moonlit Temple',
    description: 'Open packs before pale stone, silver light, and quiet ritual markings.',
    price: 1200,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#101622', '#8fa8c8', '#f7f8ff'],
    cssClass: 'openingScene-moonlitTemple',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-neon-rift',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Neon Rift',
    description: 'Open packs beside a sharp cyan and magenta rift glow.',
    price: 1700,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#020308', '#00f0ff', '#ff00bf'],
    cssClass: 'openingScene-neonRift',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-dragons-hoard',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: "Dragon's Hoard",
    description: 'Open packs over scorched treasure and ember-lit scales.',
    price: 1500,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'openingScene-dragonsHoard',
    unlockType: 'cosmetic',
  },
  {
    id: 'scene-eldritch-gate',
    category: SHOP_CATEGORIES.OPENING_SCENES,
    name: 'Eldritch Gate',
    description: 'Open packs near a green-lit threshold of old and strange power.',
    price: 1500,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.OPENING_SCENE,
    previewColors: ['#031008', '#24c96d', '#b8ffcf'],
    cssClass: 'openingScene-eldritchGate',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-arcane',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Arcane Sleeve',
    description: 'A violet sleeve with gold spellwork and a quiet magical glow.',
    price: 700,
    rarity: 'uncommon',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#120f2d', '#7d6bff', '#f4c95d'],
    cssClass: 'cardSleeve-arcane',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-gold-collector',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Gold Collector Sleeve',
    description: 'A premium black-and-gold sleeve for favorite high-value pulls.',
    price: 1000,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#060606', '#c7952d', '#fff0b3'],
    cssClass: 'cardSleeve-goldCollector',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'sleeve-galaxy',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Galaxy Sleeve',
    description: 'A starfield sleeve with blue-violet cosmic shimmer.',
    price: 1000,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#050717', '#4778ff', '#b45cff'],
    cssClass: 'cardSleeve-galaxy',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-dragon-scale',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Dragon Scale Sleeve',
    description: 'A textured red sleeve inspired by scales, ash, and flame.',
    price: 950,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#160605', '#b8281d', '#ff9f35'],
    cssClass: 'cardSleeve-dragonScale',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-moonlit',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Moonlit Sleeve',
    description: 'A silver-blue sleeve with a soft lunar edge highlight.',
    price: 800,
    rarity: 'uncommon',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#101724', '#97abc5', '#f7f9ff'],
    cssClass: 'cardSleeve-moonlit',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-neon',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Neon Sleeve',
    description: 'A black sleeve with cyan and magenta edge light.',
    price: 1200,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#03040a', '#00f5ff', '#ff00c8'],
    cssClass: 'cardSleeve-neon',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-eldritch',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Eldritch Sleeve',
    description: 'A dark green sleeve with uncanny sigils and soft toxic glow.',
    price: 950,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#04100a', '#29c96f', '#c2ffd2'],
    cssClass: 'cardSleeve-eldritch',
    unlockType: 'cosmetic',
  },
  {
    id: 'sleeve-minimal-black',
    category: SHOP_CATEGORIES.SLEEVES,
    name: 'Minimal Black Sleeve',
    description: 'A clean matte black sleeve with restrained edge detail.',
    price: 500,
    rarity: 'common',
    equipSlot: EQUIP_SLOTS.CARD_SLEEVE,
    previewColors: ['#050505', '#2a2d35', '#d9d9d9'],
    cssClass: 'cardSleeve-minimalBlack',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-clean',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Clean Tear',
    description: 'A crisp foil seam with a simple polished tear line.',
    price: 400,
    rarity: 'common',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#050711', '#dce2ee', '#f4c95d'],
    cssClass: 'tearEffect-clean',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-arcane-slice',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Arcane Slice',
    description: 'A purple magical blade cuts the wrapper with spell sparks.',
    price: 850,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#120f2d', '#8f7cff', '#f4c95d'],
    cssClass: 'tearEffect-arcaneSlice',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-lightning-rip',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Lightning Rip',
    description: 'An electric bolt races across the seam as the pack opens.',
    price: 950,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#06101f', '#4cc9f0', '#fff6a3'],
    cssClass: 'tearEffect-lightningRip',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-golden-seal-break',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Golden Seal Break',
    description: 'A gilded seal shatters into warm collector sparks.',
    price: 1100,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#090705', '#c9962e', '#fff0b8'],
    cssClass: 'tearEffect-goldenSealBreak',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'tear-galaxy-rift',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Galaxy Rift',
    description: 'A cosmic tear opens with star dust and violet-blue glow.',
    price: 1200,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'tearEffect-galaxyRift',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-neon-cutter',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Neon Cutter',
    description: 'A cyan and pink laser slices through the wrapper.',
    price: 1300,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'tearEffect-neonCutter',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-dragonfire-burn',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Dragonfire Burn',
    description: 'A hot ember burn marks the seam before the top tears away.',
    price: 1050,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'tearEffect-dragonfireBurn',
    unlockType: 'cosmetic',
  },
  {
    id: 'tear-eldritch-unseal',
    category: SHOP_CATEGORIES.TEAR_EFFECTS,
    name: 'Eldritch Unseal',
    description: 'Green runes unlock the wrapper with an uncanny glow.',
    price: 1050,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TEAR_EFFECT,
    previewColors: ['#031008', '#24c96d', '#b8ffcf'],
    cssClass: 'tearEffect-eldritchUnseal',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-classic',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Classic Reveal',
    description: 'A clean rare-pull glow with subtle sparks and a soft ring.',
    price: 450,
    rarity: 'common',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#050711', '#f4c95d', '#dce2ee'],
    cssClass: 'revealEffect-classic',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-arcane-burst',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Arcane Burst',
    description: 'A violet magic burst for eligible rare and mythic card reveals.',
    price: 900,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#120f2d', '#8f7cff', '#f4c95d'],
    cssClass: 'revealEffect-arcaneBurst',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-gold-flash',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Gold Flash',
    description: 'A bright collector-style gold flash for regular rare hits.',
    price: 950,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#090705', '#c9962e', '#fff0b8'],
    cssClass: 'revealEffect-goldFlash',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'reveal-cosmic-pull',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Cosmic Pull',
    description: 'A starry pull-in aura with blue and violet particles.',
    price: 1200,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'revealEffect-cosmicPull',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-fire-impact',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Fire Impact',
    description: 'A warm ember impact for rare and mythic non-foil pulls.',
    price: 1050,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'revealEffect-fireImpact',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-neon-pulse',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Neon Pulse',
    description: 'A cyan and magenta pulse for eligible high-rarity reveals.',
    price: 1300,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'revealEffect-neonPulse',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-moonlight',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Moonlight Reveal',
    description: 'A quiet silver reveal with pale rings and drifting motes.',
    price: 850,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#101622', '#8fa8c8', '#f7f8ff'],
    cssClass: 'revealEffect-moonlight',
    unlockType: 'cosmetic',
  },
  {
    id: 'reveal-vault-unlock',
    category: SHOP_CATEGORIES.REVEAL_EFFECTS,
    name: 'Vault Unlock',
    description: 'A vault-ring unlock flash for valuable regular pulls.',
    price: 1150,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.REVEAL_EFFECT,
    previewColors: ['#080806', '#d6a33a', '#fff1a8'],
    cssClass: 'revealEffect-vaultUnlock',
    unlockType: 'cosmetic',
  },
  {
    id: 'avatar-frame-bronze',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Bronze Frame',
    description: 'A warm bronze avatar frame for a clean collector profile.',
    price: 350,
    rarity: 'common',
    equipSlot: EQUIP_SLOTS.AVATAR_FRAME,
    previewColors: ['#14100b', '#a96f32', '#e0ad68'],
    cssClass: 'avatarFrame-bronze',
    unlockType: 'cosmetic',
  },
  {
    id: 'avatar-frame-silver',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Silver Frame',
    description: 'A cool silver avatar frame with crisp moonlit edges.',
    price: 500,
    rarity: 'uncommon',
    equipSlot: EQUIP_SLOTS.AVATAR_FRAME,
    previewColors: ['#101722', '#9fb7d6', '#f7f8ff'],
    cssClass: 'avatarFrame-silver',
    unlockType: 'cosmetic',
  },
  {
    id: 'avatar-frame-gold',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Gold Frame',
    description: 'A polished gold avatar frame for premium profiles.',
    price: 750,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.AVATAR_FRAME,
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'avatarFrame-gold',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'avatar-frame-galaxy',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Galaxy Frame',
    description: 'A blue-violet starfield frame for cosmic collectors.',
    price: 1000,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.AVATAR_FRAME,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'avatarFrame-galaxy',
    unlockType: 'cosmetic',
  },
  {
    id: 'avatar-frame-neon',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Neon Frame',
    description: 'A cyan and magenta profile frame with sharp neon glow.',
    price: 1150,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.AVATAR_FRAME,
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'avatarFrame-neon',
    unlockType: 'cosmetic',
  },
  {
    id: 'avatar-frame-mythic-flame',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Mythic Flame Frame',
    description: 'A mythic ember frame for profiles that run hot.',
    price: 1100,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.AVATAR_FRAME,
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'avatarFrame-mythicFlame',
    unlockType: 'cosmetic',
  },
  {
    id: 'profile-banner-arcane-library',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Arcane Library Banner',
    description: 'A violet-and-gold banner inspired by spell-lit archives.',
    price: 700,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.PROFILE_BANNER,
    previewColors: ['#120f2d', '#8f7cff', '#f4c95d'],
    cssClass: 'profileBanner-arcaneLibrary',
    unlockType: 'cosmetic',
  },
  {
    id: 'profile-banner-collector-vault',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Collector Vault Banner',
    description: 'A dark vault banner with warm gilded highlights.',
    price: 800,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.PROFILE_BANNER,
    previewColors: ['#090705', '#c9962e', '#fff0b8'],
    cssClass: 'profileBanner-collectorVault',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'profile-banner-galaxy',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Galaxy Banner',
    description: 'A cosmic profile banner with blue and violet star glow.',
    price: 950,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.PROFILE_BANNER,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'profileBanner-galaxy',
    unlockType: 'cosmetic',
  },
  {
    id: 'profile-banner-dragonfire',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Dragonfire Banner',
    description: 'A scorched profile banner with ember-lit edges.',
    price: 900,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.PROFILE_BANNER,
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'profileBanner-dragonfire',
    unlockType: 'cosmetic',
  },
  {
    id: 'profile-banner-neon-rift',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Neon Rift Banner',
    description: 'A blacklight banner with cyan and magenta rift energy.',
    price: 1050,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.PROFILE_BANNER,
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'profileBanner-neonRift',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-pack-goblin',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Pack Goblin',
    description: 'A playful title badge for frequent pack openers.',
    price: 250,
    rarity: 'common',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#101421', '#38d978', '#f4c95d'],
    cssClass: 'titleBadge-packGoblin',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-foil-hunter',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Foil Hunter',
    description: 'A title badge for collectors chasing shiny pulls.',
    price: 350,
    rarity: 'uncommon',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#101724', '#97abc5', '#f7f9ff'],
    cssClass: 'titleBadge-foilHunter',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-mythic-seeker',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Mythic Seeker',
    description: 'A title badge for the rarest regular pulls.',
    price: 500,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#120f2d', '#8f7cff', '#f4c95d'],
    cssClass: 'titleBadge-mythicSeeker',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-shard-baron',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Shard Baron',
    description: 'A title badge for collectors with a taste for currency.',
    price: 650,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'titleBadge-shardBaron',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-binder-mage',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Binder Mage',
    description: 'A title badge for organized collectors and page-builders.',
    price: 650,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#031008', '#24c96d', '#b8ffcf'],
    cssClass: 'titleBadge-binderMage',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-collector-supreme',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Collector Supreme',
    description: 'A premium title badge for top-tier collectors.',
    price: 950,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#090705', '#c9962e', '#fff0b8'],
    cssClass: 'titleBadge-collectorSupreme',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'title-galaxy-puller',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Galaxy Puller',
    description: 'A cosmic title badge for collectors with starry luck.',
    price: 900,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'titleBadge-galaxyPuller',
    unlockType: 'cosmetic',
  },
  {
    id: 'title-neon-chaser',
    category: SHOP_CATEGORIES.PROFILE_COSMETICS,
    name: 'Neon Chaser',
    description: 'A bright title badge for collectors chasing blacklight pulls.',
    price: 1000,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.TITLE_BADGE,
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'titleBadge-neonChaser',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-clasp-gold',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Gold Clasp',
    description: 'A polished golden clasp for a premium binder cover.',
    price: 500,
    rarity: 'rare',
    equipSlot: 'binderClasp',
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'binderClasp-gold',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-clasp-moon-silver',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Moon Silver Clasp',
    description: 'A cool silver clasp with pale moonlit shine.',
    price: 500,
    rarity: 'rare',
    equipSlot: 'binderClasp',
    previewColors: ['#101622', '#8fa8c8', '#f7f8ff'],
    cssClass: 'binderClasp-moonSilver',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-clasp-dragon-scale',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Dragon Scale Clasp',
    description: 'A scorched clasp with scale texture and ember edges.',
    price: 650,
    rarity: 'mythic',
    equipSlot: 'binderClasp',
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'binderClasp-dragonScale',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-clasp-neon-lock',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Neon Lock',
    description: 'A cyan and magenta lock clasp for bright binder builds.',
    price: 800,
    rarity: 'legendary',
    equipSlot: 'binderClasp',
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'binderClasp-neonLock',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-clasp-eldritch-seal',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Eldritch Seal',
    description: 'A green sigil clasp with strange sealed energy.',
    price: 700,
    rarity: 'mythic',
    equipSlot: 'binderClasp',
    previewColors: ['#031008', '#24c96d', '#b8ffcf'],
    cssClass: 'binderClasp-eldritchSeal',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-page-velvet-black',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Velvet Black Pages',
    description: 'Dark velvet page backing for a clean gallery look.',
    price: 450,
    rarity: 'uncommon',
    equipSlot: 'binderPageStyle',
    previewColors: ['#050505', '#151820', '#d9d9d9'],
    cssClass: 'binderPage-velvetBlack',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-page-gold-trim',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Gold Trim Pages',
    description: 'Binder pages with warm collector gold trim.',
    price: 650,
    rarity: 'rare',
    equipSlot: 'binderPageStyle',
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'binderPage-goldTrim',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-page-galaxy',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Galaxy Pages',
    description: 'Starfield pages with blue and violet drift.',
    price: 750,
    rarity: 'mythic',
    equipSlot: 'binderPageStyle',
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'binderPage-galaxy',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-page-moonlit',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Moonlit Pages',
    description: 'Cool silver-blue pages with soft lunar glow.',
    price: 650,
    rarity: 'rare',
    equipSlot: 'binderPageStyle',
    previewColors: ['#101622', '#8fa8c8', '#f7f8ff'],
    cssClass: 'binderPage-moonlit',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-page-classic-clear',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Classic Clear Sleeves',
    description: 'Transparent classic sleeve pages with restrained shine.',
    price: 350,
    rarity: 'common',
    equipSlot: 'binderPageStyle',
    previewColors: ['#0c101a', '#dce2ee', '#f8f7ff'],
    cssClass: 'binderPage-classicClear',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-slot-basic',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Basic Sleeve Frame',
    description: 'A clean slot frame for each binder pocket.',
    price: 250,
    rarity: 'common',
    equipSlot: 'binderSlotFrame',
    previewColors: ['#0c101a', '#b9bfd8', '#f8f7ff'],
    cssClass: 'binderSlot-basic',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-slot-gold',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Gold Slot Frame',
    description: 'Warm gold slot frames for premium binder pages.',
    price: 550,
    rarity: 'rare',
    equipSlot: 'binderSlotFrame',
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'binderSlot-gold',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-slot-foil',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Foil Slot Frame',
    description: 'A reflective slot frame for shiny collection displays.',
    price: 650,
    rarity: 'rare',
    equipSlot: 'binderSlotFrame',
    previewColors: ['#101724', '#97abc5', '#f7f9ff'],
    cssClass: 'binderSlot-foil',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-slot-mythic',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Mythic Slot Frame',
    description: 'A mythic-orange slot frame for high-impact pages.',
    price: 800,
    rarity: 'mythic',
    equipSlot: 'binderSlotFrame',
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'binderSlot-mythic',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-slot-neon',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Neon Slot Frame',
    description: 'A bright cyan and magenta slot frame.',
    price: 900,
    rarity: 'legendary',
    equipSlot: 'binderSlotFrame',
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'binderSlot-neon',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-aura-soft-arcane',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Soft Arcane Glow',
    description: 'A quiet violet aura around the binder cover and pages.',
    price: 500,
    rarity: 'rare',
    equipSlot: 'binderAura',
    previewColors: ['#120f2d', '#8f7cff', '#f4c95d'],
    cssClass: 'binderAura-softArcane',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-aura-golden-collector',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Golden Collector Glow',
    description: 'A warm golden aura for collector binders.',
    price: 700,
    rarity: 'mythic',
    equipSlot: 'binderAura',
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'binderAura-goldenCollector',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'binder-aura-galaxy-drift',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Galaxy Drift',
    description: 'A slow blue-violet drift around binder surfaces.',
    price: 800,
    rarity: 'mythic',
    equipSlot: 'binderAura',
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'binderAura-galaxyDrift',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-aura-dragon-ember',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Dragon Ember Glow',
    description: 'A hot ember glow for fiery binder collections.',
    price: 800,
    rarity: 'mythic',
    equipSlot: 'binderAura',
    previewColors: ['#130604', '#b82418', '#ffba4a'],
    cssClass: 'binderAura-dragonEmber',
    unlockType: 'cosmetic',
  },
  {
    id: 'binder-aura-neon-pulse',
    category: SHOP_CATEGORIES.BINDER_COSMETICS,
    name: 'Neon Pulse',
    description: 'A cyan and magenta pulse for blacklight binder displays.',
    price: 950,
    rarity: 'legendary',
    equipSlot: 'binderAura',
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'binderAura-neonPulse',
    unlockType: 'cosmetic',
  },
  {
    id: 'display-case-3-card-starter',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: '3-Card Starter Display',
    description: 'A compact display case for three favorite pulls.',
    price: 700,
    rarity: 'common',
    equipSlot: 'displayCase',
    previewColors: ['#0c101a', '#b9bfd8', '#f8f7ff'],
    cssClass: 'displayCase-starter',
    unlockType: 'cosmetic',
    capacity: 3,
  },
  {
    id: 'display-case-5-card-collector',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: '5-Card Collector Display',
    description: 'A balanced case for showcasing a favorite mini-gallery.',
    price: 1100,
    rarity: 'uncommon',
    equipSlot: 'displayCase',
    previewColors: ['#080806', '#c9962e', '#fff0b8'],
    cssClass: 'displayCase-collector',
    unlockType: 'cosmetic',
    capacity: 5,
    featured: true,
  },
  {
    id: 'display-case-10-card-trophy',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: '10-Card Trophy Case',
    description: 'A larger trophy case for a full row of standout cards.',
    price: 1800,
    rarity: 'mythic',
    equipSlot: 'displayCase',
    previewColors: ['#11100d', '#c9962e', '#fff0b8'],
    cssClass: 'displayCase-trophy',
    unlockType: 'cosmetic',
    capacity: 10,
  },
  {
    id: 'display-case-foil-gallery',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: 'Foil Gallery Case',
    description: 'A reflective gallery case made for favorite foil pulls.',
    price: 1500,
    rarity: 'rare',
    equipSlot: 'displayCase',
    previewColors: ['#101724', '#97abc5', '#f7f9ff'],
    cssClass: 'displayCase-foilGallery',
    unlockType: 'cosmetic',
    capacity: 5,
  },
  {
    id: 'display-case-legendary-vault',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: 'Legendary Vault Case',
    description: 'A vault-style case for your most important pulls.',
    price: 2200,
    rarity: 'legendary',
    equipSlot: 'displayCase',
    previewColors: ['#090705', '#c9962e', '#fff0b8'],
    cssClass: 'displayCase-legendaryVault',
    unlockType: 'cosmetic',
    capacity: 5,
  },
  {
    id: 'display-case-galaxy',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: 'Galaxy Case',
    description: 'A cosmic display case with blue-violet starfield glow.',
    price: 1700,
    rarity: 'mythic',
    equipSlot: 'displayCase',
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'displayCase-galaxy',
    unlockType: 'cosmetic',
    capacity: 5,
  },
  {
    id: 'display-case-neon',
    category: SHOP_CATEGORIES.DISPLAY_CASES,
    name: 'Neon Case',
    description: 'A cyan and magenta display case for blacklight favorites.',
    price: 1900,
    rarity: 'legendary',
    equipSlot: 'displayCase',
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'displayCase-neon',
    unlockType: 'cosmetic',
    capacity: 5,
  },
  {
    id: 'trade-skin-classic-market',
    category: SHOP_CATEGORIES.TRADE_SKINS,
    name: 'Classic Market Table',
    description: 'A warm tabletop trade booth with practical borders and soft market light.',
    price: 550,
    rarity: 'common',
    equipSlot: EQUIP_SLOTS.TRADE_SKIN,
    previewColors: ['#11100d', '#b6854d', '#f4d29b'],
    cssClass: 'tradeSkin-classicMarket',
    unlockType: 'cosmetic',
  },
  {
    id: 'trade-skin-arcane-contract',
    category: SHOP_CATEGORIES.TRADE_SKINS,
    name: 'Arcane Contract Table',
    description: 'A violet contract table with gold sigils and spell-lit offer panels.',
    price: 950,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TRADE_SKIN,
    previewColors: ['#120f2d', '#8f7cff', '#f4c95d'],
    cssClass: 'tradeSkin-arcaneContract',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'trade-skin-treasure-exchange',
    category: SHOP_CATEGORIES.TRADE_SKINS,
    name: 'Treasure Exchange',
    description: 'A dark exchange counter with gilded trim and collector-vault glow.',
    price: 1100,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TRADE_SKIN,
    previewColors: ['#090705', '#c9962e', '#fff0b8'],
    cssClass: 'tradeSkin-treasureExchange',
    unlockType: 'cosmetic',
  },
  {
    id: 'trade-skin-neon-terminal',
    category: SHOP_CATEGORIES.TRADE_SKINS,
    name: 'Neon Trade Terminal',
    description: 'A blacklight trading terminal with cyan-magenta panels and sharp value readouts.',
    price: 1300,
    rarity: 'legendary',
    equipSlot: EQUIP_SLOTS.TRADE_SKIN,
    previewColors: ['#020308', '#00f5ff', '#ff00c8'],
    cssClass: 'tradeSkin-neonTerminal',
    unlockType: 'cosmetic',
    featured: true,
  },
  {
    id: 'trade-skin-guild-hall',
    category: SHOP_CATEGORIES.TRADE_SKINS,
    name: 'Guild Hall',
    description: 'A formal guild table with deep banners, brass trim, and balanced offer lanes.',
    price: 900,
    rarity: 'rare',
    equipSlot: EQUIP_SLOTS.TRADE_SKIN,
    previewColors: ['#101421', '#7c2438', '#d6a33a'],
    cssClass: 'tradeSkin-guildHall',
    unlockType: 'cosmetic',
  },
  {
    id: 'trade-skin-cosmic-exchange',
    category: SHOP_CATEGORIES.TRADE_SKINS,
    name: 'Cosmic Exchange',
    description: 'A starfield trade booth with blue-violet drift and luminous comparison cards.',
    price: 1200,
    rarity: 'mythic',
    equipSlot: EQUIP_SLOTS.TRADE_SKIN,
    previewColors: ['#02030c', '#3564ff', '#c069ff'],
    cssClass: 'tradeSkin-cosmicExchange',
    unlockType: 'cosmetic',
  },
];

export function getShopItemById(itemId) {
  return SHOP_CATALOG.find((item) => item.id === itemId) || null;
}

export function getShopItemsByCategory(category) {
  return SHOP_CATALOG.filter((item) => item.category === category);
}

export function getFeaturedShopItems() {
  return SHOP_CATALOG.filter((item) => item.featured);
}

export function getShopItemsByEquipSlot(equipSlot) {
  return SHOP_CATALOG.filter((item) => item.equipSlot === equipSlot);
}
